language: node_js
os: linux
dist: xenial
cache:
  npm: false
script:
  - 'npm test'
before_deploy:
  - 'npm run build'
deploy:
  edge: true
  provider: surge
  project: ./build/
  domain: reason-react-realworld-example-app.surge.sh
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
